//============================================================================
// Imported from nu8051 (machine-cycle-accurate Intel 8051/8052 core, SystemVerilog)
// Source: rtl/nu8051_decode_ops.svh, commit e2c97de0fabb3b3baa1eb98a15284bc74ef92f4e
// Do not hand-edit; re-import from upstream. The M72 integration wrapper is
// rtl/mcu.sv (distilled from nu8051 rtl/m72/mcu.sv), NOT a raw re-import.
//============================================================================
// GENERATED by sw/gen_decode.py -- DO NOT EDIT.
// Decode field ENCODINGS (core_design.md §3).  Split out of
// nu8051_decode.svh so blocks that consume a field without holding
// the 256-arm case (nu8051_alu.sv) can include just this.
// generator: gen_decode-4
// instructions.json sha256: 761c0abd7aacff507a0469837b2a1342c42eb661f6278f9d8abd4ace4a39148b

// NOTE: no include guard - module-scope localparams, one include per
// module (Verilator shares `define state across the compilation unit).

// verilator lint_off UNUSEDPARAM
localparam logic [2:0] SH_A = 3'd0;
localparam logic [2:0] SH_B = 3'd1;
localparam logic [2:0] SH_C1 = 3'd2;
localparam logic [2:0] SH_C2 = 3'd3;
localparam logic [2:0] SH_C3 = 3'd4;
localparam logic [2:0] SH_D = 3'd5;
localparam logic [2:0] SH_E = 3'd6;
localparam logic [2:0] SH_F = 3'd7;
localparam logic [3:0] CLS_MOV = 4'd0;
localparam logic [3:0] CLS_ARITH = 4'd1;
localparam logic [3:0] CLS_LOGIC = 4'd2;
localparam logic [3:0] CLS_BIT = 4'd3;
localparam logic [3:0] CLS_BRANCH = 4'd4;
localparam logic [3:0] CLS_CALL = 4'd5;
localparam logic [3:0] CLS_MOVX = 4'd6;
localparam logic [3:0] CLS_MOVC = 4'd7;
localparam logic [3:0] CLS_MISC = 4'd8;
localparam logic [3:0] OPK_NONE = 4'd0;
localparam logic [3:0] OPK_A = 4'd1;
localparam logic [3:0] OPK_B = 4'd2;
localparam logic [3:0] OPK_RN = 4'd3;
localparam logic [3:0] OPK_RI = 4'd4;
localparam logic [3:0] OPK_DIR = 4'd5;
localparam logic [3:0] OPK_IMM = 4'd6;
localparam logic [3:0] OPK_BIT = 4'd7;
localparam logic [3:0] OPK_C = 4'd8;
localparam logic [3:0] OPK_DPTR = 4'd9;
localparam logic [3:0] OPK_STACK = 4'd10;
localparam logic [3:0] OPK_XRAM_RI = 4'd11;
localparam logic [3:0] OPK_XRAM_DPTR = 4'd12;
localparam logic [3:0] OPK_CODE_DPTR = 4'd13;
localparam logic [3:0] OPK_CODE_PC = 4'd14;
localparam logic [3:0] OPK_IMM16 = 4'd15;
localparam logic [4:0] ALU_NOP = 5'd0;
localparam logic [4:0] ALU_PASS = 5'd1;
localparam logic [4:0] ALU_ADD = 5'd2;
localparam logic [4:0] ALU_ADDC = 5'd3;
localparam logic [4:0] ALU_SUBB = 5'd4;
localparam logic [4:0] ALU_INC = 5'd5;
localparam logic [4:0] ALU_DEC = 5'd6;
localparam logic [4:0] ALU_ANL = 5'd7;
localparam logic [4:0] ALU_ORL = 5'd8;
localparam logic [4:0] ALU_XRL = 5'd9;
localparam logic [4:0] ALU_CLRA = 5'd10;
localparam logic [4:0] ALU_CPLA = 5'd11;
localparam logic [4:0] ALU_SWAP = 5'd12;
localparam logic [4:0] ALU_RL = 5'd13;
localparam logic [4:0] ALU_RR = 5'd14;
localparam logic [4:0] ALU_RLC = 5'd15;
localparam logic [4:0] ALU_RRC = 5'd16;
localparam logic [4:0] ALU_DA = 5'd17;
localparam logic [4:0] ALU_MUL = 5'd18;
localparam logic [4:0] ALU_DIV = 5'd19;
localparam logic [4:0] ALU_CJNE = 5'd20;
localparam logic [4:0] ALU_XCH = 5'd21;
localparam logic [4:0] ALU_XCHD = 5'd22;
localparam logic [4:0] ALU_PUSH = 5'd23;
localparam logic [4:0] ALU_POP = 5'd24;
localparam logic [4:0] ALU_BITSET = 5'd25;
localparam logic [4:0] ALU_BITCLR = 5'd26;
localparam logic [4:0] ALU_BITCPL = 5'd27;
localparam logic [4:0] ALU_BITMOV = 5'd28;
localparam logic [4:0] ALU_BITANL = 5'd29;
localparam logic [4:0] ALU_BITORL = 5'd30;
localparam logic [4:0] ALU_RSVD = 5'd31;
localparam logic [3:0] CND_NONE = 4'd0;
localparam logic [3:0] CND_ALWAYS = 4'd1;
localparam logic [3:0] CND_Z = 4'd2;
localparam logic [3:0] CND_NZ = 4'd3;
localparam logic [3:0] CND_C = 4'd4;
localparam logic [3:0] CND_NC = 4'd5;
localparam logic [3:0] CND_BIT = 4'd6;
localparam logic [3:0] CND_NBIT = 4'd7;
localparam logic [3:0] CND_JBC = 4'd8;
localparam logic [3:0] CND_CJNE = 4'd9;
localparam logic [3:0] CND_DJNZ = 4'd10;
localparam logic [2:0] TGT_NONE = 3'd0;
localparam logic [2:0] TGT_REL = 3'd1;
localparam logic [2:0] TGT_A11 = 3'd2;
localparam logic [2:0] TGT_A16 = 3'd3;
localparam logic [2:0] TGT_ADPTR = 3'd4;
// verilator lint_on UNUSEDPARAM
