//============================================================================
// Imported from nu8051 (machine-cycle-accurate Intel 8051/8052 core, SystemVerilog)
// Source: rtl/nu8051_decode.svh, commit ad28e1b655ec7a38054174beaed157f013ea5643
// Do not hand-edit; re-import from upstream. The M72 integration wrapper is
// rtl/mcu.sv (distilled from nu8051 rtl/m72/mcu.sv), NOT a raw re-import.
//============================================================================
// GENERATED by sw/gen_decode.py -- DO NOT EDIT.
// Source: docs/facts/instructions.json (F0.2); contract: core_design.md §3.
// generator: gen_decode-4
// instructions.json sha256: 761c0abd7aacff507a0469837b2a1342c42eb661f6278f9d8abd4ace4a39148b
//
// Fields: d_len d_cycles d_shape d_class d_alu_op d_src d_dst d_rmw
//         d_cond d_flagw + d_bitn (C4.5 `/bit` complement, QUESTION-P45-1)
//         + d_tgt d_src2 (C4.6 target form / second source, QUESTION-P46-1)
//         + d_reti (C4.7 RETI vs RET, QUESTION-P47-1).
// Flat discrete decode signals (NOT a packed struct - PLAN §5 worker
// rule).  Field encodings live in rtl/nu8051_defs.svh; this file only
// uses the DEC_/OPK_/ALU_/SH_/CLS_/CND_ localparams from there.
//
// shape histogram: A=127, B=35, C1=4, C2=56, C3=24, D=6, E=2, F=2 (=256)
// pilot (Phase-3) opcode closure: 56 opcodes

// NOTE: no include guard - module-scope declarations, one include per
// module (Verilator shares `define state across the compilation unit).

// field encodings (shared with nu8051_alu.sv etc.)
`include "nu8051_decode_ops.svh"

// verilator lint_off UNUSEDPARAM
localparam string NU8051_DECODE_ISET_SHA = "761c0abd7aacff507a0469837b2a1342c42eb661f6278f9d8abd4ace4a39148b";
// verilator lint_on UNUSEDPARAM

always_comb begin
    unique case (ir)
    8'h00: begin  // NOP
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MISC; d_alu_op = ALU_NOP;
        d_src = OPK_NONE; d_dst = OPK_NONE; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h01: begin  // AJMP addr11
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BRANCH; d_alu_op = ALU_PASS;
        d_src = OPK_NONE; d_dst = OPK_NONE; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_A11; d_reti = 1'b0;
    end
    8'h02: begin  // LJMP addr16
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_BRANCH; d_alu_op = ALU_PASS;
        d_src = OPK_NONE; d_dst = OPK_NONE; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_A16; d_reti = 1'b0;
    end
    8'h03: begin  // RR A
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_RR;
        d_src = OPK_A; d_dst = OPK_A; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h04: begin  // INC A
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_INC;
        d_src = OPK_A; d_dst = OPK_A; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h05: begin  // INC direct
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_ARITH; d_alu_op = ALU_INC;
        d_src = OPK_DIR; d_dst = OPK_DIR; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h06: begin  // INC @R0
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_INC;
        d_src = OPK_RI; d_dst = OPK_RI; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h07: begin  // INC @R1
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_INC;
        d_src = OPK_RI; d_dst = OPK_RI; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h08: begin  // INC R0
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_INC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h09: begin  // INC R1
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_INC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h0A: begin  // INC R2
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_INC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h0B: begin  // INC R3
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_INC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h0C: begin  // INC R4
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_INC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h0D: begin  // INC R5
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_INC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h0E: begin  // INC R6
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_INC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h0F: begin  // INC R7
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_INC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h10: begin  // JBC bit,rel
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_BRANCH; d_alu_op = ALU_BITCLR;
        d_src = OPK_BIT; d_dst = OPK_BIT; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_JBC; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'h11: begin  // ACALL addr11
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_CALL; d_alu_op = ALU_PASS;
        d_src = OPK_STACK; d_dst = OPK_STACK; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_A11; d_reti = 1'b0;
    end
    8'h12: begin  // LCALL addr16
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_CALL; d_alu_op = ALU_PASS;
        d_src = OPK_STACK; d_dst = OPK_STACK; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_A16; d_reti = 1'b0;
    end
    8'h13: begin  // RRC A
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_RRC;
        d_src = OPK_C; d_dst = OPK_C; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd1; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h14: begin  // DEC A
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_DEC;
        d_src = OPK_A; d_dst = OPK_A; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h15: begin  // DEC direct
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_ARITH; d_alu_op = ALU_DEC;
        d_src = OPK_DIR; d_dst = OPK_DIR; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h16: begin  // DEC @R0
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_DEC;
        d_src = OPK_RI; d_dst = OPK_RI; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h17: begin  // DEC @R1
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_DEC;
        d_src = OPK_RI; d_dst = OPK_RI; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h18: begin  // DEC R0
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_DEC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h19: begin  // DEC R1
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_DEC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h1A: begin  // DEC R2
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_DEC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h1B: begin  // DEC R3
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_DEC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h1C: begin  // DEC R4
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_DEC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h1D: begin  // DEC R5
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_DEC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h1E: begin  // DEC R6
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_DEC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h1F: begin  // DEC R7
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_DEC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h20: begin  // JB bit,rel
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_BRANCH; d_alu_op = ALU_PASS;
        d_src = OPK_BIT; d_dst = OPK_NONE; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_BIT; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'h21: begin  // AJMP addr11
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BRANCH; d_alu_op = ALU_PASS;
        d_src = OPK_NONE; d_dst = OPK_NONE; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_A11; d_reti = 1'b0;
    end
    8'h22: begin  // RET
        d_len = 2'd1; d_cycles = 3'd2; d_shape = SH_C1;
        d_class = CLS_CALL; d_alu_op = ALU_PASS;
        d_src = OPK_STACK; d_dst = OPK_STACK; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h23: begin  // RL A
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_RL;
        d_src = OPK_A; d_dst = OPK_A; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h24: begin  // ADD A,#data
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_ARITH; d_alu_op = ALU_ADD;
        d_src = OPK_IMM; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h25: begin  // ADD A,direct
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_ARITH; d_alu_op = ALU_ADD;
        d_src = OPK_DIR; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h26: begin  // ADD A,@R0
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_ADD;
        d_src = OPK_RI; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h27: begin  // ADD A,@R1
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_ADD;
        d_src = OPK_RI; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h28: begin  // ADD A,R0
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_ADD;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h29: begin  // ADD A,R1
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_ADD;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h2A: begin  // ADD A,R2
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_ADD;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h2B: begin  // ADD A,R3
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_ADD;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h2C: begin  // ADD A,R4
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_ADD;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h2D: begin  // ADD A,R5
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_ADD;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h2E: begin  // ADD A,R6
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_ADD;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h2F: begin  // ADD A,R7
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_ADD;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h30: begin  // JNB bit,rel
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_BRANCH; d_alu_op = ALU_PASS;
        d_src = OPK_BIT; d_dst = OPK_NONE; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NBIT; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'h31: begin  // ACALL addr11
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_CALL; d_alu_op = ALU_PASS;
        d_src = OPK_STACK; d_dst = OPK_STACK; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_A11; d_reti = 1'b0;
    end
    8'h32: begin  // RETI
        d_len = 2'd1; d_cycles = 3'd2; d_shape = SH_C1;
        d_class = CLS_CALL; d_alu_op = ALU_PASS;
        d_src = OPK_STACK; d_dst = OPK_STACK; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b1;
    end
    8'h33: begin  // RLC A
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_RLC;
        d_src = OPK_C; d_dst = OPK_C; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd1; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h34: begin  // ADDC A,#data
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_ARITH; d_alu_op = ALU_ADDC;
        d_src = OPK_IMM; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h35: begin  // ADDC A,direct
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_ARITH; d_alu_op = ALU_ADDC;
        d_src = OPK_DIR; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h36: begin  // ADDC A,@R0
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_ADDC;
        d_src = OPK_RI; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h37: begin  // ADDC A,@R1
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_ADDC;
        d_src = OPK_RI; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h38: begin  // ADDC A,R0
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_ADDC;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h39: begin  // ADDC A,R1
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_ADDC;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h3A: begin  // ADDC A,R2
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_ADDC;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h3B: begin  // ADDC A,R3
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_ADDC;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h3C: begin  // ADDC A,R4
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_ADDC;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h3D: begin  // ADDC A,R5
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_ADDC;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h3E: begin  // ADDC A,R6
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_ADDC;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h3F: begin  // ADDC A,R7
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_ADDC;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h40: begin  // JC rel
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BRANCH; d_alu_op = ALU_PASS;
        d_src = OPK_C; d_dst = OPK_NONE; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_C; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'h41: begin  // AJMP addr11
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BRANCH; d_alu_op = ALU_PASS;
        d_src = OPK_NONE; d_dst = OPK_NONE; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_A11; d_reti = 1'b0;
    end
    8'h42: begin  // ORL direct,A
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_LOGIC; d_alu_op = ALU_ORL;
        d_src = OPK_DIR; d_dst = OPK_DIR; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h43: begin  // ORL direct,#data
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_LOGIC; d_alu_op = ALU_ORL;
        d_src = OPK_IMM; d_dst = OPK_DIR; d_src2 = OPK_DIR;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h44: begin  // ORL A,#data
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_LOGIC; d_alu_op = ALU_ORL;
        d_src = OPK_IMM; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h45: begin  // ORL A,direct
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_LOGIC; d_alu_op = ALU_ORL;
        d_src = OPK_DIR; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h46: begin  // ORL A,@R0
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_ORL;
        d_src = OPK_RI; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h47: begin  // ORL A,@R1
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_ORL;
        d_src = OPK_RI; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h48: begin  // ORL A,R0
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_ORL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h49: begin  // ORL A,R1
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_ORL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h4A: begin  // ORL A,R2
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_ORL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h4B: begin  // ORL A,R3
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_ORL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h4C: begin  // ORL A,R4
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_ORL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h4D: begin  // ORL A,R5
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_ORL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h4E: begin  // ORL A,R6
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_ORL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h4F: begin  // ORL A,R7
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_ORL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h50: begin  // JNC rel
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BRANCH; d_alu_op = ALU_PASS;
        d_src = OPK_C; d_dst = OPK_NONE; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NC; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'h51: begin  // ACALL addr11
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_CALL; d_alu_op = ALU_PASS;
        d_src = OPK_STACK; d_dst = OPK_STACK; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_A11; d_reti = 1'b0;
    end
    8'h52: begin  // ANL direct,A
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_LOGIC; d_alu_op = ALU_ANL;
        d_src = OPK_DIR; d_dst = OPK_DIR; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h53: begin  // ANL direct,#data
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_LOGIC; d_alu_op = ALU_ANL;
        d_src = OPK_IMM; d_dst = OPK_DIR; d_src2 = OPK_DIR;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h54: begin  // ANL A,#data
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_LOGIC; d_alu_op = ALU_ANL;
        d_src = OPK_IMM; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h55: begin  // ANL A,direct
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_LOGIC; d_alu_op = ALU_ANL;
        d_src = OPK_DIR; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h56: begin  // ANL A,@R0
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_ANL;
        d_src = OPK_RI; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h57: begin  // ANL A,@R1
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_ANL;
        d_src = OPK_RI; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h58: begin  // ANL A,R0
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_ANL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h59: begin  // ANL A,R1
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_ANL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h5A: begin  // ANL A,R2
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_ANL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h5B: begin  // ANL A,R3
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_ANL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h5C: begin  // ANL A,R4
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_ANL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h5D: begin  // ANL A,R5
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_ANL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h5E: begin  // ANL A,R6
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_ANL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h5F: begin  // ANL A,R7
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_ANL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h60: begin  // JZ rel
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BRANCH; d_alu_op = ALU_PASS;
        d_src = OPK_A; d_dst = OPK_NONE; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_Z; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'h61: begin  // AJMP addr11
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BRANCH; d_alu_op = ALU_PASS;
        d_src = OPK_NONE; d_dst = OPK_NONE; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_A11; d_reti = 1'b0;
    end
    8'h62: begin  // XRL direct,A
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_LOGIC; d_alu_op = ALU_XRL;
        d_src = OPK_DIR; d_dst = OPK_DIR; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h63: begin  // XRL direct,#data
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_LOGIC; d_alu_op = ALU_XRL;
        d_src = OPK_IMM; d_dst = OPK_DIR; d_src2 = OPK_DIR;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h64: begin  // XRL A,#data
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_LOGIC; d_alu_op = ALU_XRL;
        d_src = OPK_IMM; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h65: begin  // XRL A,direct
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_LOGIC; d_alu_op = ALU_XRL;
        d_src = OPK_DIR; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h66: begin  // XRL A,@R0
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_XRL;
        d_src = OPK_RI; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h67: begin  // XRL A,@R1
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_XRL;
        d_src = OPK_RI; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h68: begin  // XRL A,R0
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_XRL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h69: begin  // XRL A,R1
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_XRL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h6A: begin  // XRL A,R2
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_XRL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h6B: begin  // XRL A,R3
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_XRL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h6C: begin  // XRL A,R4
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_XRL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h6D: begin  // XRL A,R5
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_XRL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h6E: begin  // XRL A,R6
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_XRL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h6F: begin  // XRL A,R7
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_XRL;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h70: begin  // JNZ rel
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BRANCH; d_alu_op = ALU_PASS;
        d_src = OPK_A; d_dst = OPK_NONE; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NZ; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'h71: begin  // ACALL addr11
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_CALL; d_alu_op = ALU_PASS;
        d_src = OPK_STACK; d_dst = OPK_STACK; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_A11; d_reti = 1'b0;
    end
    8'h72: begin  // ORL C,bit
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BIT; d_alu_op = ALU_BITORL;
        d_src = OPK_BIT; d_dst = OPK_C; d_src2 = OPK_C;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd1; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h73: begin  // JMP @A+DPTR
        d_len = 2'd1; d_cycles = 3'd2; d_shape = SH_C1;
        d_class = CLS_BRANCH; d_alu_op = ALU_PASS;
        d_src = OPK_DPTR; d_dst = OPK_NONE; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_ADPTR; d_reti = 1'b0;
    end
    8'h74: begin  // MOV A,#data
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_IMM; d_dst = OPK_A; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h75: begin  // MOV direct,#data
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_IMM; d_dst = OPK_DIR; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h76: begin  // MOV @R0,#data
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_IMM; d_dst = OPK_RI; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h77: begin  // MOV @R1,#data
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_IMM; d_dst = OPK_RI; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h78: begin  // MOV R0,#data
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_IMM; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h79: begin  // MOV R1,#data
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_IMM; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h7A: begin  // MOV R2,#data
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_IMM; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h7B: begin  // MOV R3,#data
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_IMM; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h7C: begin  // MOV R4,#data
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_IMM; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h7D: begin  // MOV R5,#data
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_IMM; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h7E: begin  // MOV R6,#data
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_IMM; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h7F: begin  // MOV R7,#data
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_IMM; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h80: begin  // SJMP rel
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BRANCH; d_alu_op = ALU_PASS;
        d_src = OPK_NONE; d_dst = OPK_NONE; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'h81: begin  // AJMP addr11
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BRANCH; d_alu_op = ALU_PASS;
        d_src = OPK_NONE; d_dst = OPK_NONE; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_A11; d_reti = 1'b0;
    end
    8'h82: begin  // ANL C,bit
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BIT; d_alu_op = ALU_BITANL;
        d_src = OPK_BIT; d_dst = OPK_C; d_src2 = OPK_C;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd1; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h83: begin  // MOVC A,@A+PC
        d_len = 2'd1; d_cycles = 3'd2; d_shape = SH_E;
        d_class = CLS_MOVC; d_alu_op = ALU_PASS;
        d_src = OPK_CODE_PC; d_dst = OPK_A; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h84: begin  // DIV AB
        d_len = 2'd1; d_cycles = 3'd4; d_shape = SH_F;
        d_class = CLS_ARITH; d_alu_op = ALU_DIV;
        d_src = OPK_B; d_dst = OPK_B; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd5; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h85: begin  // MOV direct,direct
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_DIR; d_dst = OPK_DIR; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h86: begin  // MOV direct,@R0
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_RI; d_dst = OPK_DIR; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h87: begin  // MOV direct,@R1
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_RI; d_dst = OPK_DIR; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h88: begin  // MOV direct,R0
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_RN; d_dst = OPK_DIR; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h89: begin  // MOV direct,R1
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_RN; d_dst = OPK_DIR; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h8A: begin  // MOV direct,R2
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_RN; d_dst = OPK_DIR; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h8B: begin  // MOV direct,R3
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_RN; d_dst = OPK_DIR; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h8C: begin  // MOV direct,R4
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_RN; d_dst = OPK_DIR; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h8D: begin  // MOV direct,R5
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_RN; d_dst = OPK_DIR; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h8E: begin  // MOV direct,R6
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_RN; d_dst = OPK_DIR; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h8F: begin  // MOV direct,R7
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_RN; d_dst = OPK_DIR; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h90: begin  // MOV DPTR,#data16
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_IMM16; d_dst = OPK_DPTR; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h91: begin  // ACALL addr11
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_CALL; d_alu_op = ALU_PASS;
        d_src = OPK_STACK; d_dst = OPK_STACK; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_A11; d_reti = 1'b0;
    end
    8'h92: begin  // MOV bit,C
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BIT; d_alu_op = ALU_BITMOV;
        d_src = OPK_C; d_dst = OPK_BIT; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h93: begin  // MOVC A,@A+DPTR
        d_len = 2'd1; d_cycles = 3'd2; d_shape = SH_E;
        d_class = CLS_MOVC; d_alu_op = ALU_PASS;
        d_src = OPK_CODE_DPTR; d_dst = OPK_A; d_src2 = OPK_DPTR;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h94: begin  // SUBB A,#data
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_ARITH; d_alu_op = ALU_SUBB;
        d_src = OPK_IMM; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h95: begin  // SUBB A,direct
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_ARITH; d_alu_op = ALU_SUBB;
        d_src = OPK_DIR; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h96: begin  // SUBB A,@R0
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_SUBB;
        d_src = OPK_RI; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h97: begin  // SUBB A,@R1
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_SUBB;
        d_src = OPK_RI; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h98: begin  // SUBB A,R0
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_SUBB;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h99: begin  // SUBB A,R1
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_SUBB;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h9A: begin  // SUBB A,R2
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_SUBB;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h9B: begin  // SUBB A,R3
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_SUBB;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h9C: begin  // SUBB A,R4
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_SUBB;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h9D: begin  // SUBB A,R5
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_SUBB;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h9E: begin  // SUBB A,R6
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_SUBB;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'h9F: begin  // SUBB A,R7
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_SUBB;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_C;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd7; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hA0: begin  // ORL C,/bit
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BIT; d_alu_op = ALU_BITORL;
        d_src = OPK_BIT; d_dst = OPK_C; d_src2 = OPK_C;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd1; d_bitn = 1'b1; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hA1: begin  // AJMP addr11
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BRANCH; d_alu_op = ALU_PASS;
        d_src = OPK_NONE; d_dst = OPK_NONE; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_A11; d_reti = 1'b0;
    end
    8'hA2: begin  // MOV C,bit
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_BIT; d_alu_op = ALU_BITMOV;
        d_src = OPK_BIT; d_dst = OPK_C; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd1; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hA3: begin  // INC DPTR
        d_len = 2'd1; d_cycles = 3'd2; d_shape = SH_C1;
        d_class = CLS_ARITH; d_alu_op = ALU_INC;
        d_src = OPK_DPTR; d_dst = OPK_DPTR; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hA4: begin  // MUL AB
        d_len = 2'd1; d_cycles = 3'd4; d_shape = SH_F;
        d_class = CLS_ARITH; d_alu_op = ALU_MUL;
        d_src = OPK_B; d_dst = OPK_B; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd5; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hA5: begin  // RESERVED
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MISC; d_alu_op = ALU_RSVD;
        d_src = OPK_NONE; d_dst = OPK_NONE; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hA6: begin  // MOV @R0,direct
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_DIR; d_dst = OPK_RI; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hA7: begin  // MOV @R1,direct
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_DIR; d_dst = OPK_RI; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hA8: begin  // MOV R0,direct
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_DIR; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hA9: begin  // MOV R1,direct
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_DIR; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hAA: begin  // MOV R2,direct
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_DIR; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hAB: begin  // MOV R3,direct
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_DIR; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hAC: begin  // MOV R4,direct
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_DIR; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hAD: begin  // MOV R5,direct
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_DIR; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hAE: begin  // MOV R6,direct
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_DIR; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hAF: begin  // MOV R7,direct
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_DIR; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hB0: begin  // ANL C,/bit
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BIT; d_alu_op = ALU_BITANL;
        d_src = OPK_BIT; d_dst = OPK_C; d_src2 = OPK_C;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd1; d_bitn = 1'b1; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hB1: begin  // ACALL addr11
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_CALL; d_alu_op = ALU_PASS;
        d_src = OPK_STACK; d_dst = OPK_STACK; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_A11; d_reti = 1'b0;
    end
    8'hB2: begin  // CPL bit
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_BIT; d_alu_op = ALU_BITCPL;
        d_src = OPK_BIT; d_dst = OPK_BIT; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hB3: begin  // CPL C
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_BIT; d_alu_op = ALU_BITCPL;
        d_src = OPK_C; d_dst = OPK_C; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd1; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hB4: begin  // CJNE A,#data,rel
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_BRANCH; d_alu_op = ALU_CJNE;
        d_src = OPK_IMM; d_dst = OPK_C; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_CJNE; d_flagw = 3'd1; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'hB5: begin  // CJNE A,direct,rel
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_BRANCH; d_alu_op = ALU_CJNE;
        d_src = OPK_DIR; d_dst = OPK_C; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_CJNE; d_flagw = 3'd1; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'hB6: begin  // CJNE @R0,#data,rel
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_BRANCH; d_alu_op = ALU_CJNE;
        d_src = OPK_IMM; d_dst = OPK_C; d_src2 = OPK_RI;
        d_rmw = 1'b0; d_cond = CND_CJNE; d_flagw = 3'd1; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'hB7: begin  // CJNE @R1,#data,rel
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_BRANCH; d_alu_op = ALU_CJNE;
        d_src = OPK_IMM; d_dst = OPK_C; d_src2 = OPK_RI;
        d_rmw = 1'b0; d_cond = CND_CJNE; d_flagw = 3'd1; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'hB8: begin  // CJNE R0,#data,rel
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_BRANCH; d_alu_op = ALU_CJNE;
        d_src = OPK_IMM; d_dst = OPK_C; d_src2 = OPK_RN;
        d_rmw = 1'b0; d_cond = CND_CJNE; d_flagw = 3'd1; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'hB9: begin  // CJNE R1,#data,rel
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_BRANCH; d_alu_op = ALU_CJNE;
        d_src = OPK_IMM; d_dst = OPK_C; d_src2 = OPK_RN;
        d_rmw = 1'b0; d_cond = CND_CJNE; d_flagw = 3'd1; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'hBA: begin  // CJNE R2,#data,rel
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_BRANCH; d_alu_op = ALU_CJNE;
        d_src = OPK_IMM; d_dst = OPK_C; d_src2 = OPK_RN;
        d_rmw = 1'b0; d_cond = CND_CJNE; d_flagw = 3'd1; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'hBB: begin  // CJNE R3,#data,rel
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_BRANCH; d_alu_op = ALU_CJNE;
        d_src = OPK_IMM; d_dst = OPK_C; d_src2 = OPK_RN;
        d_rmw = 1'b0; d_cond = CND_CJNE; d_flagw = 3'd1; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'hBC: begin  // CJNE R4,#data,rel
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_BRANCH; d_alu_op = ALU_CJNE;
        d_src = OPK_IMM; d_dst = OPK_C; d_src2 = OPK_RN;
        d_rmw = 1'b0; d_cond = CND_CJNE; d_flagw = 3'd1; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'hBD: begin  // CJNE R5,#data,rel
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_BRANCH; d_alu_op = ALU_CJNE;
        d_src = OPK_IMM; d_dst = OPK_C; d_src2 = OPK_RN;
        d_rmw = 1'b0; d_cond = CND_CJNE; d_flagw = 3'd1; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'hBE: begin  // CJNE R6,#data,rel
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_BRANCH; d_alu_op = ALU_CJNE;
        d_src = OPK_IMM; d_dst = OPK_C; d_src2 = OPK_RN;
        d_rmw = 1'b0; d_cond = CND_CJNE; d_flagw = 3'd1; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'hBF: begin  // CJNE R7,#data,rel
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_BRANCH; d_alu_op = ALU_CJNE;
        d_src = OPK_IMM; d_dst = OPK_C; d_src2 = OPK_RN;
        d_rmw = 1'b0; d_cond = CND_CJNE; d_flagw = 3'd1; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'hC0: begin  // PUSH direct
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_PUSH;
        d_src = OPK_DIR; d_dst = OPK_STACK; d_src2 = OPK_STACK;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hC1: begin  // AJMP addr11
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BRANCH; d_alu_op = ALU_PASS;
        d_src = OPK_NONE; d_dst = OPK_NONE; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_A11; d_reti = 1'b0;
    end
    8'hC2: begin  // CLR bit
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_BIT; d_alu_op = ALU_BITCLR;
        d_src = OPK_NONE; d_dst = OPK_BIT; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hC3: begin  // CLR C
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_BIT; d_alu_op = ALU_BITCLR;
        d_src = OPK_NONE; d_dst = OPK_C; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd1; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hC4: begin  // SWAP A
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_SWAP;
        d_src = OPK_A; d_dst = OPK_A; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hC5: begin  // XCH A,direct
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_MOV; d_alu_op = ALU_XCH;
        d_src = OPK_DIR; d_dst = OPK_DIR; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hC6: begin  // XCH A,@R0
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_XCH;
        d_src = OPK_RI; d_dst = OPK_RI; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hC7: begin  // XCH A,@R1
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_XCH;
        d_src = OPK_RI; d_dst = OPK_RI; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hC8: begin  // XCH A,R0
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_XCH;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hC9: begin  // XCH A,R1
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_XCH;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hCA: begin  // XCH A,R2
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_XCH;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hCB: begin  // XCH A,R3
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_XCH;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hCC: begin  // XCH A,R4
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_XCH;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hCD: begin  // XCH A,R5
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_XCH;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hCE: begin  // XCH A,R6
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_XCH;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hCF: begin  // XCH A,R7
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_XCH;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hD0: begin  // POP direct
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_MOV; d_alu_op = ALU_POP;
        d_src = OPK_STACK; d_dst = OPK_DIR; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hD1: begin  // ACALL addr11
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_CALL; d_alu_op = ALU_PASS;
        d_src = OPK_STACK; d_dst = OPK_STACK; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_A11; d_reti = 1'b0;
    end
    8'hD2: begin  // SETB bit
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_BIT; d_alu_op = ALU_BITSET;
        d_src = OPK_NONE; d_dst = OPK_BIT; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hD3: begin  // SETB C
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_BIT; d_alu_op = ALU_BITSET;
        d_src = OPK_NONE; d_dst = OPK_C; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd1; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hD4: begin  // DA A
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_ARITH; d_alu_op = ALU_DA;
        d_src = OPK_A; d_dst = OPK_A; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd1; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hD5: begin  // DJNZ direct,rel
        d_len = 2'd3; d_cycles = 3'd2; d_shape = SH_C3;
        d_class = CLS_BRANCH; d_alu_op = ALU_DEC;
        d_src = OPK_DIR; d_dst = OPK_DIR; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_DJNZ; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'hD6: begin  // XCHD A,@R0
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_XCHD;
        d_src = OPK_RI; d_dst = OPK_RI; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hD7: begin  // XCHD A,@R1
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_XCHD;
        d_src = OPK_RI; d_dst = OPK_RI; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hD8: begin  // DJNZ R0,rel
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BRANCH; d_alu_op = ALU_DEC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_DJNZ; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'hD9: begin  // DJNZ R1,rel
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BRANCH; d_alu_op = ALU_DEC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_DJNZ; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'hDA: begin  // DJNZ R2,rel
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BRANCH; d_alu_op = ALU_DEC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_DJNZ; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'hDB: begin  // DJNZ R3,rel
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BRANCH; d_alu_op = ALU_DEC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_DJNZ; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'hDC: begin  // DJNZ R4,rel
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BRANCH; d_alu_op = ALU_DEC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_DJNZ; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'hDD: begin  // DJNZ R5,rel
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BRANCH; d_alu_op = ALU_DEC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_DJNZ; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'hDE: begin  // DJNZ R6,rel
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BRANCH; d_alu_op = ALU_DEC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_DJNZ; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'hDF: begin  // DJNZ R7,rel
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BRANCH; d_alu_op = ALU_DEC;
        d_src = OPK_RN; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_DJNZ; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_REL; d_reti = 1'b0;
    end
    8'hE0: begin  // MOVX A,@DPTR
        d_len = 2'd1; d_cycles = 3'd2; d_shape = SH_D;
        d_class = CLS_MOVX; d_alu_op = ALU_PASS;
        d_src = OPK_XRAM_DPTR; d_dst = OPK_A; d_src2 = OPK_DPTR;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hE1: begin  // AJMP addr11
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_BRANCH; d_alu_op = ALU_PASS;
        d_src = OPK_NONE; d_dst = OPK_NONE; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_A11; d_reti = 1'b0;
    end
    8'hE2: begin  // MOVX A,@R0
        d_len = 2'd1; d_cycles = 3'd2; d_shape = SH_D;
        d_class = CLS_MOVX; d_alu_op = ALU_PASS;
        d_src = OPK_XRAM_RI; d_dst = OPK_A; d_src2 = OPK_RN;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hE3: begin  // MOVX A,@R1
        d_len = 2'd1; d_cycles = 3'd2; d_shape = SH_D;
        d_class = CLS_MOVX; d_alu_op = ALU_PASS;
        d_src = OPK_XRAM_RI; d_dst = OPK_A; d_src2 = OPK_RN;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hE4: begin  // CLR A
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_CLRA;
        d_src = OPK_NONE; d_dst = OPK_A; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hE5: begin  // MOV A,direct
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_DIR; d_dst = OPK_A; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hE6: begin  // MOV A,@R0
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_RI; d_dst = OPK_A; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hE7: begin  // MOV A,@R1
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_RI; d_dst = OPK_A; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hE8: begin  // MOV A,R0
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hE9: begin  // MOV A,R1
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hEA: begin  // MOV A,R2
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hEB: begin  // MOV A,R3
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hEC: begin  // MOV A,R4
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hED: begin  // MOV A,R5
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hEE: begin  // MOV A,R6
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hEF: begin  // MOV A,R7
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_RN; d_dst = OPK_A; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hF0: begin  // MOVX @DPTR,A
        d_len = 2'd1; d_cycles = 3'd2; d_shape = SH_D;
        d_class = CLS_MOVX; d_alu_op = ALU_PASS;
        d_src = OPK_DPTR; d_dst = OPK_XRAM_DPTR; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hF1: begin  // ACALL addr11
        d_len = 2'd2; d_cycles = 3'd2; d_shape = SH_C2;
        d_class = CLS_CALL; d_alu_op = ALU_PASS;
        d_src = OPK_STACK; d_dst = OPK_STACK; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_ALWAYS; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_A11; d_reti = 1'b0;
    end
    8'hF2: begin  // MOVX @R0,A
        d_len = 2'd1; d_cycles = 3'd2; d_shape = SH_D;
        d_class = CLS_MOVX; d_alu_op = ALU_PASS;
        d_src = OPK_RN; d_dst = OPK_XRAM_RI; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hF3: begin  // MOVX @R1,A
        d_len = 2'd1; d_cycles = 3'd2; d_shape = SH_D;
        d_class = CLS_MOVX; d_alu_op = ALU_PASS;
        d_src = OPK_RN; d_dst = OPK_XRAM_RI; d_src2 = OPK_A;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hF4: begin  // CPL A
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_LOGIC; d_alu_op = ALU_CPLA;
        d_src = OPK_A; d_dst = OPK_A; d_src2 = OPK_NONE;
        d_rmw = 1'b1; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hF5: begin  // MOV direct,A
        d_len = 2'd2; d_cycles = 3'd1; d_shape = SH_B;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_A; d_dst = OPK_DIR; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hF6: begin  // MOV @R0,A
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_A; d_dst = OPK_RI; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hF7: begin  // MOV @R1,A
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_A; d_dst = OPK_RI; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hF8: begin  // MOV R0,A
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_A; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hF9: begin  // MOV R1,A
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_A; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hFA: begin  // MOV R2,A
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_A; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hFB: begin  // MOV R3,A
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_A; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hFC: begin  // MOV R4,A
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_A; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hFD: begin  // MOV R5,A
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_A; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hFE: begin  // MOV R6,A
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_A; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    8'hFF: begin  // MOV R7,A
        d_len = 2'd1; d_cycles = 3'd1; d_shape = SH_A;
        d_class = CLS_MOV; d_alu_op = ALU_PASS;
        d_src = OPK_A; d_dst = OPK_RN; d_src2 = OPK_NONE;
        d_rmw = 1'b0; d_cond = CND_NONE; d_flagw = 3'd0; d_bitn = 1'b0; d_tgt = TGT_NONE; d_reti = 1'b0;
    end
    endcase
end
