//============================================================================
// Imported from nu8051 (machine-cycle-accurate Intel 8051/8052 core, SystemVerilog)
// Source: rtl/nu8051_cfg.svh, commit ad28e1b655ec7a38054174beaed157f013ea5643
// Do not hand-edit; re-import from upstream. The M72 integration wrapper is
// rtl/mcu.sv (distilled from nu8051 rtl/m72/mcu.sv), NOT a raw re-import.
//============================================================================
// GENERATED by sw/gen_cfg.py from cfg/nu8051_cfg.json -- DO NOT EDIT.
// Shared RTL/refsim constants; publication mechanism core_design.md 5.2.
// All symbols are NU8051_CFG_-prefixed so this file can be `include`d
// into a module that has parameters of the same stem (QUESTION-T23-6).
// cfg sha256: ecae254260e4d878595baa75821749569d892610e6c4cd83feda4736e7f6246e
`ifndef NU8051_CFG_SVH
`define NU8051_CFG_SVH

localparam string NU8051_CFG_SHA = "ecae254260e4d878595baa75821749569d892610e6c4cd83feda4736e7f6246e";

// PQ5: value returned by reads of unimplemented SFR addresses and, when
// P_8052==0, indirect reads of 80H-FFH. Writes to those are dropped.
// (core_design.md 5.2/9, OPEN_QUESTIONS PQ5)
localparam logic [7:0] NU8051_CFG_UNIMPL_RD = 8'hFF;

// Default value of the P_8052 parameter / refsim 'init' command when a
// session does not specify one.
localparam int NU8051_CFG_P8052_DEFAULT = 1;

// Internal ROM address width (12 = 4K, 13 = 8K). core_design 1.1.
localparam int NU8051_CFG_ROM_AW = 13;

`endif // NU8051_CFG_SVH
