// GENERATED by sw/gen_ucore_tables.py from docs/V20BITS.TXT and
// docs/pla3_outputs.txt.  DO NOT HAND-EDIT.  Gate G0
// (`python3 sw/check_ucore_tables.py`) proves this file byte-matches
// the C++ reference model's own tables.
//
// The group-decode PLA: a 2-bit decode-mode prefix + the 8 opcode
// bits -> a 14-bit vector.  Three separate 256-entry tables
// (sim/pla3_table.h):
//     prefix 01 -> native   (native V20/V30 first-byte opcode)
//     prefix 00 -> mode8080 (8080 emulation mode, entered by BRKEM)
//     prefix 11 -> ext      (second byte of the 0F extension page)
//
// Bit numbering matches the model: the dumps print the vector
// MSB-first as b0..b13 and b0 is stored in bit 13, so XOP[3:0]
// (b10..b13) lands in the low nibble.
//
// `include this inside a module body.  Pure combinational case ROMs;
// no state, no clock.

  // --- decode-mode prefixes ---
  localparam logic [1:0] PLA3_MODE_8080 = 2'b00;
  localparam logic [1:0] PLA3_MODE_NATIVE = 2'b01;
  localparam logic [1:0] PLA3_MODE_EXT    = 2'b11;

  // --- named columns (sim/pla3_table.h::Col) ---
  localparam logic [13:0] PLA3_BYTE_ONLY       = 14'h2000; // b0  byte-width-only data op, no W bit
  localparam logic [13:0] PLA3_W_FROM_BIT0     = 14'h1000; // b1  operand width = opcode bit 0
  localparam logic [13:0] PLA3_ONE_BYTE_LOGIC  = 14'h0800; // b2  1BL: executed by logic, no microcode
  localparam logic [13:0] PLA3_ACC_W_OPERAND   = 14'h0400; // b3  implicit AL/AW operand, width from W
  localparam logic [13:0] PLA3_SREG_MOV        = 14'h0200; // b4  MOV to/from a segment register (8C/8E)
  localparam logic [13:0] PLA3_HAS_MODRM       = 14'h0100; // b5  a ModR/M byte follows
  localparam logic [13:0] PLA3_MODRM_STORE     = 14'h0080; // b6  r/m operand written without being read
  localparam logic [13:0] PLA3_DIR_FROM_BIT1   = 14'h0040; // b7  source/destination direction = opcode bit 1
  localparam logic [13:0] PLA3_NATIVE_HI       = 14'h0020; // b8  native opcode >= 0x80 (map-half select)
  localparam logic [13:0] PLA3_INCDEC_NO_CY    = 14'h0010; // b9  INC/DEC class: CY must not be updated
  // b10..b13 = XOP[3:0], a 4-bit auxiliary op-select field.
  localparam logic [13:0] PLA3_XOP_MASK      = 14'h000F;

  // --- XOP[3:0] when ONE_BYTE_LOGIC is set (sim/pla3_table.h::Bl1Op) ---
  localparam logic [3:0] PLA3_BL1_SEG_PREFIX = 4'h0; // 26/2E/36/3E
  localparam logic [3:0] PLA3_BL1_EXT_PREFIX = 4'h1; // native 0F, 8080 ED
  localparam logic [3:0] PLA3_BL1_SET_DIR    = 4'h2; // STD
  localparam logic [3:0] PLA3_BL1_CLR_DIR    = 4'h3; // CLD
  localparam logic [3:0] PLA3_BL1_SET_IE     = 4'h4; // EI (STI)
  localparam logic [3:0] PLA3_BL1_CLR_IE     = 4'h5; // DI (CLI)
  localparam logic [3:0] PLA3_BL1_SET_CY     = 4'h6; // STC
  localparam logic [3:0] PLA3_BL1_CLR_CY     = 4'h7; // CLC
  localparam logic [3:0] PLA3_BL1_REPC_PFX   = 4'h8; // REPC
  localparam logic [3:0] PLA3_BL1_REPNC_PFX  = 4'h9; // REPNC
  localparam logic [3:0] PLA3_BL1_NOT_CY     = 4'hA; // CMC
  localparam logic [3:0] PLA3_BL1_HALT       = 4'hB; // HALT
  localparam logic [3:0] PLA3_BL1_REP_PFX    = 4'hC; // REP/REPE
  localparam logic [3:0] PLA3_BL1_REPNE_PFX  = 4'hD; // REPNE
  localparam logic [3:0] PLA3_BL1_LOCK_ALIAS = 4'hE; // undocumented F1
  localparam logic [3:0] PLA3_BL1_LOCK       = 4'hF; // BUSLOCK

  // --- named accessors (sim/pla3_table.h constexpr predicates) ---
  function automatic logic pla3_byte_only(input logic [13:0] pla_v);
    pla3_byte_only = pla_v[13];
  endfunction
  function automatic logic pla3_w_from_bit0(input logic [13:0] pla_v);
    pla3_w_from_bit0 = pla_v[12];
  endfunction
  function automatic logic pla3_one_byte_logic(input logic [13:0] pla_v);
    pla3_one_byte_logic = pla_v[11];
  endfunction
  function automatic logic pla3_acc_w_operand(input logic [13:0] pla_v);
    pla3_acc_w_operand = pla_v[10];
  endfunction
  function automatic logic pla3_sreg_mov(input logic [13:0] pla_v);
    pla3_sreg_mov = pla_v[9];
  endfunction
  function automatic logic pla3_has_modrm(input logic [13:0] pla_v);
    pla3_has_modrm = pla_v[8];
  endfunction
  function automatic logic pla3_modrm_store(input logic [13:0] pla_v);
    pla3_modrm_store = pla_v[7];
  endfunction
  function automatic logic pla3_dir_from_bit1(input logic [13:0] pla_v);
    pla3_dir_from_bit1 = pla_v[6];
  endfunction
  function automatic logic pla3_native_hi(input logic [13:0] pla_v);
    pla3_native_hi = pla_v[5];
  endfunction
  function automatic logic pla3_incdec_no_cy(input logic [13:0] pla_v);
    pla3_incdec_no_cy = pla_v[4];
  endfunction
  function automatic logic [3:0] pla3_xop(input logic [13:0] pla_v);
    pla3_xop = pla_v[3:0];
  endfunction

  // sim/pla3_table.h::is_prefix -- consume the byte and re-decode.
  function automatic logic pla3_is_prefix(input logic [13:0] pla_v);
    logic p;
    p = 1'b0;
    if (pla_v[11]) begin
      case (pla_v[3:0])
        PLA3_BL1_SEG_PREFIX, PLA3_BL1_EXT_PREFIX,
        PLA3_BL1_REPC_PFX,   PLA3_BL1_REPNC_PFX,
        PLA3_BL1_REP_PFX,    PLA3_BL1_REPNE_PFX,
        PLA3_BL1_LOCK_ALIAS, PLA3_BL1_LOCK: p = 1'b1;
        default: p = 1'b0;
      endcase
    end
    pla3_is_prefix = p;
  endfunction

  // --- prefix 01: native ---
  function automatic logic [13:0] pla3_native(input logic [7:0] pla_op);
    case (pla_op)
      8'h00: pla3_native = 14'h1140;
      8'h01: pla3_native = 14'h1140;
      8'h02: pla3_native = 14'h1140;
      8'h03: pla3_native = 14'h1140;
      8'h04: pla3_native = 14'h1400;
      8'h05: pla3_native = 14'h1400;
      8'h06: pla3_native = 14'h0000;
      8'h07: pla3_native = 14'h0001;
      8'h08: pla3_native = 14'h1140;
      8'h09: pla3_native = 14'h1140;
      8'h0A: pla3_native = 14'h1140;
      8'h0B: pla3_native = 14'h1140;
      8'h0C: pla3_native = 14'h1400;
      8'h0D: pla3_native = 14'h1400;
      8'h0E: pla3_native = 14'h0000;
      8'h0F: pla3_native = 14'h0801;
      8'h10: pla3_native = 14'h1140;
      8'h11: pla3_native = 14'h1140;
      8'h12: pla3_native = 14'h1140;
      8'h13: pla3_native = 14'h1140;
      8'h14: pla3_native = 14'h1400;
      8'h15: pla3_native = 14'h1400;
      8'h16: pla3_native = 14'h0000;
      8'h17: pla3_native = 14'h0001;
      8'h18: pla3_native = 14'h1140;
      8'h19: pla3_native = 14'h1140;
      8'h1A: pla3_native = 14'h1140;
      8'h1B: pla3_native = 14'h1140;
      8'h1C: pla3_native = 14'h1400;
      8'h1D: pla3_native = 14'h1400;
      8'h1E: pla3_native = 14'h0000;
      8'h1F: pla3_native = 14'h0001;
      8'h20: pla3_native = 14'h1140;
      8'h21: pla3_native = 14'h1140;
      8'h22: pla3_native = 14'h1140;
      8'h23: pla3_native = 14'h1140;
      8'h24: pla3_native = 14'h1400;
      8'h25: pla3_native = 14'h1400;
      8'h26: pla3_native = 14'h0800;
      8'h27: pla3_native = 14'h200A;
      8'h28: pla3_native = 14'h1140;
      8'h29: pla3_native = 14'h1140;
      8'h2A: pla3_native = 14'h1140;
      8'h2B: pla3_native = 14'h1140;
      8'h2C: pla3_native = 14'h1400;
      8'h2D: pla3_native = 14'h1400;
      8'h2E: pla3_native = 14'h0800;
      8'h2F: pla3_native = 14'h200A;
      8'h30: pla3_native = 14'h1140;
      8'h31: pla3_native = 14'h1140;
      8'h32: pla3_native = 14'h1140;
      8'h33: pla3_native = 14'h1140;
      8'h34: pla3_native = 14'h1400;
      8'h35: pla3_native = 14'h1400;
      8'h36: pla3_native = 14'h0800;
      8'h37: pla3_native = 14'h200A;
      8'h38: pla3_native = 14'h1140;
      8'h39: pla3_native = 14'h1140;
      8'h3A: pla3_native = 14'h1140;
      8'h3B: pla3_native = 14'h1140;
      8'h3C: pla3_native = 14'h1400;
      8'h3D: pla3_native = 14'h1400;
      8'h3E: pla3_native = 14'h0800;
      8'h3F: pla3_native = 14'h200A;
      8'h40: pla3_native = 14'h001C;
      8'h41: pla3_native = 14'h001C;
      8'h42: pla3_native = 14'h001C;
      8'h43: pla3_native = 14'h001C;
      8'h44: pla3_native = 14'h001C;
      8'h45: pla3_native = 14'h001C;
      8'h46: pla3_native = 14'h001C;
      8'h47: pla3_native = 14'h001C;
      8'h48: pla3_native = 14'h001C;
      8'h49: pla3_native = 14'h001C;
      8'h4A: pla3_native = 14'h001C;
      8'h4B: pla3_native = 14'h001C;
      8'h4C: pla3_native = 14'h001C;
      8'h4D: pla3_native = 14'h001C;
      8'h4E: pla3_native = 14'h001C;
      8'h4F: pla3_native = 14'h001C;
      8'h50: pla3_native = 14'h0000;
      8'h51: pla3_native = 14'h0000;
      8'h52: pla3_native = 14'h0000;
      8'h53: pla3_native = 14'h0000;
      8'h54: pla3_native = 14'h0000;
      8'h55: pla3_native = 14'h0000;
      8'h56: pla3_native = 14'h0000;
      8'h57: pla3_native = 14'h0000;
      8'h58: pla3_native = 14'h0000;
      8'h59: pla3_native = 14'h0000;
      8'h5A: pla3_native = 14'h0000;
      8'h5B: pla3_native = 14'h0000;
      8'h5C: pla3_native = 14'h0000;
      8'h5D: pla3_native = 14'h0000;
      8'h5E: pla3_native = 14'h0000;
      8'h5F: pla3_native = 14'h0000;
      8'h60: pla3_native = 14'h0000;
      8'h61: pla3_native = 14'h0000;
      8'h62: pla3_native = 14'h0100;
      8'h63: pla3_native = 14'h0100;
      8'h64: pla3_native = 14'h0809;
      8'h65: pla3_native = 14'h0808;
      8'h66: pla3_native = 14'h0100;
      8'h67: pla3_native = 14'h0100;
      8'h68: pla3_native = 14'h0000;
      8'h69: pla3_native = 14'h0104;
      8'h6A: pla3_native = 14'h0000;
      8'h6B: pla3_native = 14'h0104;
      8'h6C: pla3_native = 14'h1006;
      8'h6D: pla3_native = 14'h1006;
      8'h6E: pla3_native = 14'h1006;
      8'h6F: pla3_native = 14'h1006;
      8'h70: pla3_native = 14'h0000;
      8'h71: pla3_native = 14'h0000;
      8'h72: pla3_native = 14'h0000;
      8'h73: pla3_native = 14'h0000;
      8'h74: pla3_native = 14'h0000;
      8'h75: pla3_native = 14'h0000;
      8'h76: pla3_native = 14'h0000;
      8'h77: pla3_native = 14'h0000;
      8'h78: pla3_native = 14'h0000;
      8'h79: pla3_native = 14'h0000;
      8'h7A: pla3_native = 14'h0000;
      8'h7B: pla3_native = 14'h0000;
      8'h7C: pla3_native = 14'h0000;
      8'h7D: pla3_native = 14'h0000;
      8'h7E: pla3_native = 14'h0000;
      8'h7F: pla3_native = 14'h0000;
      8'h80: pla3_native = 14'h1124;
      8'h81: pla3_native = 14'h1124;
      8'h82: pla3_native = 14'h1124;
      8'h83: pla3_native = 14'h1124;
      8'h84: pla3_native = 14'h1124;
      8'h85: pla3_native = 14'h1124;
      8'h86: pla3_native = 14'h1124;
      8'h87: pla3_native = 14'h1124;
      8'h88: pla3_native = 14'h11E0;
      8'h89: pla3_native = 14'h11E0;
      8'h8A: pla3_native = 14'h1160;
      8'h8B: pla3_native = 14'h1160;
      8'h8C: pla3_native = 14'h03E1;
      8'h8D: pla3_native = 14'h01A0;
      8'h8E: pla3_native = 14'h0361;
      8'h8F: pla3_native = 14'h01A0;
      8'h90: pla3_native = 14'h0020;
      8'h91: pla3_native = 14'h0020;
      8'h92: pla3_native = 14'h0020;
      8'h93: pla3_native = 14'h0020;
      8'h94: pla3_native = 14'h0020;
      8'h95: pla3_native = 14'h0020;
      8'h96: pla3_native = 14'h0020;
      8'h97: pla3_native = 14'h0020;
      8'h98: pla3_native = 14'h0020;
      8'h99: pla3_native = 14'h0020;
      8'h9A: pla3_native = 14'h0020;
      8'h9B: pla3_native = 14'h0020;
      8'h9C: pla3_native = 14'h0020;
      8'h9D: pla3_native = 14'h0020;
      8'h9E: pla3_native = 14'h0020;
      8'h9F: pla3_native = 14'h0020;
      8'hA0: pla3_native = 14'h1420;
      8'hA1: pla3_native = 14'h1420;
      8'hA2: pla3_native = 14'h1420;
      8'hA3: pla3_native = 14'h1420;
      8'hA4: pla3_native = 14'h1420;
      8'hA5: pla3_native = 14'h1420;
      8'hA6: pla3_native = 14'h142E;
      8'hA7: pla3_native = 14'h142E;
      8'hA8: pla3_native = 14'h1420;
      8'hA9: pla3_native = 14'h1420;
      8'hAA: pla3_native = 14'h1420;
      8'hAB: pla3_native = 14'h1420;
      8'hAC: pla3_native = 14'h1420;
      8'hAD: pla3_native = 14'h1420;
      8'hAE: pla3_native = 14'h142E;
      8'hAF: pla3_native = 14'h142E;
      8'hB0: pla3_native = 14'h2020;
      8'hB1: pla3_native = 14'h2020;
      8'hB2: pla3_native = 14'h2020;
      8'hB3: pla3_native = 14'h2020;
      8'hB4: pla3_native = 14'h2020;
      8'hB5: pla3_native = 14'h2020;
      8'hB6: pla3_native = 14'h2020;
      8'hB7: pla3_native = 14'h2020;
      8'hB8: pla3_native = 14'h0020;
      8'hB9: pla3_native = 14'h0020;
      8'hBA: pla3_native = 14'h0020;
      8'hBB: pla3_native = 14'h0020;
      8'hBC: pla3_native = 14'h0020;
      8'hBD: pla3_native = 14'h0020;
      8'hBE: pla3_native = 14'h0020;
      8'hBF: pla3_native = 14'h0020;
      8'hC0: pla3_native = 14'h116E;
      8'hC1: pla3_native = 14'h116E;
      8'hC2: pla3_native = 14'h0020;
      8'hC3: pla3_native = 14'h0020;
      8'hC4: pla3_native = 14'h0120;
      8'hC5: pla3_native = 14'h0120;
      8'hC6: pla3_native = 14'h11A0;
      8'hC7: pla3_native = 14'h11A0;
      8'hC8: pla3_native = 14'h0020;
      8'hC9: pla3_native = 14'h0020;
      8'hCA: pla3_native = 14'h0020;
      8'hCB: pla3_native = 14'h0020;
      8'hCC: pla3_native = 14'h0020;
      8'hCD: pla3_native = 14'h0020;
      8'hCE: pla3_native = 14'h0020;
      8'hCF: pla3_native = 14'h0020;
      8'hD0: pla3_native = 14'h1120;
      8'hD1: pla3_native = 14'h1120;
      8'hD2: pla3_native = 14'h1120;
      8'hD3: pla3_native = 14'h1120;
      8'hD4: pla3_native = 14'h2020;
      8'hD5: pla3_native = 14'h2020;
      8'hD6: pla3_native = 14'h2020;
      8'hD7: pla3_native = 14'h2020;
      8'hD8: pla3_native = 14'h0120;
      8'hD9: pla3_native = 14'h0120;
      8'hDA: pla3_native = 14'h0120;
      8'hDB: pla3_native = 14'h0120;
      8'hDC: pla3_native = 14'h0120;
      8'hDD: pla3_native = 14'h0120;
      8'hDE: pla3_native = 14'h0120;
      8'hDF: pla3_native = 14'h0120;
      8'hE0: pla3_native = 14'h106E;
      8'hE1: pla3_native = 14'h106E;
      8'hE2: pla3_native = 14'h0020;
      8'hE3: pla3_native = 14'h0020;
      8'hE4: pla3_native = 14'h142F;
      8'hE5: pla3_native = 14'h142F;
      8'hE6: pla3_native = 14'h142F;
      8'hE7: pla3_native = 14'h142F;
      8'hE8: pla3_native = 14'h0020;
      8'hE9: pla3_native = 14'h0020;
      8'hEA: pla3_native = 14'h0020;
      8'hEB: pla3_native = 14'h0020;
      8'hEC: pla3_native = 14'h142F;
      8'hED: pla3_native = 14'h142F;
      8'hEE: pla3_native = 14'h142F;
      8'hEF: pla3_native = 14'h142F;
      8'hF0: pla3_native = 14'h082F;
      8'hF1: pla3_native = 14'h082E;
      8'hF2: pla3_native = 14'h082D;
      8'hF3: pla3_native = 14'h082C;
      8'hF4: pla3_native = 14'h082B;
      8'hF5: pla3_native = 14'h082A;
      8'hF6: pla3_native = 14'h113B;
      8'hF7: pla3_native = 14'h113B;
      8'hF8: pla3_native = 14'h0827;
      8'hF9: pla3_native = 14'h0826;
      8'hFA: pla3_native = 14'h0825;
      8'hFB: pla3_native = 14'h0824;
      8'hFC: pla3_native = 14'h0823;
      8'hFD: pla3_native = 14'h0822;
      8'hFE: pla3_native = 14'h113B;
      8'hFF: pla3_native = 14'h113B;
      default: pla3_native = 14'h0000;
    endcase
  endfunction

  // --- prefix 00: mode8080 ---
  function automatic logic [13:0] pla3_mode8080(input logic [7:0] pla_op);
    case (pla_op)
      8'h00: pla3_mode8080 = 14'h0000;
      8'h01: pla3_mode8080 = 14'h0000;
      8'h02: pla3_mode8080 = 14'h2000;
      8'h03: pla3_mode8080 = 14'h0000;
      8'h04: pla3_mode8080 = 14'h214C;
      8'h05: pla3_mode8080 = 14'h214C;
      8'h06: pla3_mode8080 = 14'h2040;
      8'h07: pla3_mode8080 = 14'h2000;
      8'h08: pla3_mode8080 = 14'h0000;
      8'h09: pla3_mode8080 = 14'h000D;
      8'h0A: pla3_mode8080 = 14'h2000;
      8'h0B: pla3_mode8080 = 14'h0000;
      8'h0C: pla3_mode8080 = 14'h214C;
      8'h0D: pla3_mode8080 = 14'h214C;
      8'h0E: pla3_mode8080 = 14'h2040;
      8'h0F: pla3_mode8080 = 14'h2000;
      8'h10: pla3_mode8080 = 14'h0000;
      8'h11: pla3_mode8080 = 14'h0000;
      8'h12: pla3_mode8080 = 14'h2000;
      8'h13: pla3_mode8080 = 14'h0000;
      8'h14: pla3_mode8080 = 14'h214C;
      8'h15: pla3_mode8080 = 14'h214C;
      8'h16: pla3_mode8080 = 14'h2040;
      8'h17: pla3_mode8080 = 14'h2000;
      8'h18: pla3_mode8080 = 14'h0000;
      8'h19: pla3_mode8080 = 14'h000D;
      8'h1A: pla3_mode8080 = 14'h2000;
      8'h1B: pla3_mode8080 = 14'h0000;
      8'h1C: pla3_mode8080 = 14'h214C;
      8'h1D: pla3_mode8080 = 14'h214C;
      8'h1E: pla3_mode8080 = 14'h2040;
      8'h1F: pla3_mode8080 = 14'h2000;
      8'h20: pla3_mode8080 = 14'h0000;
      8'h21: pla3_mode8080 = 14'h0000;
      8'h22: pla3_mode8080 = 14'h0000;
      8'h23: pla3_mode8080 = 14'h0000;
      8'h24: pla3_mode8080 = 14'h214C;
      8'h25: pla3_mode8080 = 14'h214C;
      8'h26: pla3_mode8080 = 14'h2040;
      8'h27: pla3_mode8080 = 14'h200A;
      8'h28: pla3_mode8080 = 14'h0000;
      8'h29: pla3_mode8080 = 14'h000D;
      8'h2A: pla3_mode8080 = 14'h0000;
      8'h2B: pla3_mode8080 = 14'h0000;
      8'h2C: pla3_mode8080 = 14'h214C;
      8'h2D: pla3_mode8080 = 14'h214C;
      8'h2E: pla3_mode8080 = 14'h2040;
      8'h2F: pla3_mode8080 = 14'h0000;
      8'h30: pla3_mode8080 = 14'h0000;
      8'h31: pla3_mode8080 = 14'h0000;
      8'h32: pla3_mode8080 = 14'h2000;
      8'h33: pla3_mode8080 = 14'h0000;
      8'h34: pla3_mode8080 = 14'h214C;
      8'h35: pla3_mode8080 = 14'h214C;
      8'h36: pla3_mode8080 = 14'h2040;
      8'h37: pla3_mode8080 = 14'h0806;
      8'h38: pla3_mode8080 = 14'h0000;
      8'h39: pla3_mode8080 = 14'h000D;
      8'h3A: pla3_mode8080 = 14'h2000;
      8'h3B: pla3_mode8080 = 14'h0000;
      8'h3C: pla3_mode8080 = 14'h214C;
      8'h3D: pla3_mode8080 = 14'h214C;
      8'h3E: pla3_mode8080 = 14'h2040;
      8'h3F: pla3_mode8080 = 14'h080A;
      8'h40: pla3_mode8080 = 14'h2100;
      8'h41: pla3_mode8080 = 14'h2100;
      8'h42: pla3_mode8080 = 14'h2100;
      8'h43: pla3_mode8080 = 14'h2100;
      8'h44: pla3_mode8080 = 14'h2100;
      8'h45: pla3_mode8080 = 14'h2100;
      8'h46: pla3_mode8080 = 14'h2100;
      8'h47: pla3_mode8080 = 14'h2100;
      8'h48: pla3_mode8080 = 14'h2100;
      8'h49: pla3_mode8080 = 14'h2100;
      8'h4A: pla3_mode8080 = 14'h2100;
      8'h4B: pla3_mode8080 = 14'h2100;
      8'h4C: pla3_mode8080 = 14'h2100;
      8'h4D: pla3_mode8080 = 14'h2100;
      8'h4E: pla3_mode8080 = 14'h2100;
      8'h4F: pla3_mode8080 = 14'h2100;
      8'h50: pla3_mode8080 = 14'h2100;
      8'h51: pla3_mode8080 = 14'h2100;
      8'h52: pla3_mode8080 = 14'h2100;
      8'h53: pla3_mode8080 = 14'h2100;
      8'h54: pla3_mode8080 = 14'h2100;
      8'h55: pla3_mode8080 = 14'h2100;
      8'h56: pla3_mode8080 = 14'h2100;
      8'h57: pla3_mode8080 = 14'h2100;
      8'h58: pla3_mode8080 = 14'h2100;
      8'h59: pla3_mode8080 = 14'h2100;
      8'h5A: pla3_mode8080 = 14'h2100;
      8'h5B: pla3_mode8080 = 14'h2100;
      8'h5C: pla3_mode8080 = 14'h2100;
      8'h5D: pla3_mode8080 = 14'h2100;
      8'h5E: pla3_mode8080 = 14'h2100;
      8'h5F: pla3_mode8080 = 14'h2100;
      8'h60: pla3_mode8080 = 14'h2100;
      8'h61: pla3_mode8080 = 14'h2100;
      8'h62: pla3_mode8080 = 14'h2100;
      8'h63: pla3_mode8080 = 14'h2100;
      8'h64: pla3_mode8080 = 14'h2100;
      8'h65: pla3_mode8080 = 14'h2100;
      8'h66: pla3_mode8080 = 14'h2100;
      8'h67: pla3_mode8080 = 14'h2100;
      8'h68: pla3_mode8080 = 14'h2100;
      8'h69: pla3_mode8080 = 14'h2100;
      8'h6A: pla3_mode8080 = 14'h2100;
      8'h6B: pla3_mode8080 = 14'h2100;
      8'h6C: pla3_mode8080 = 14'h2100;
      8'h6D: pla3_mode8080 = 14'h2100;
      8'h6E: pla3_mode8080 = 14'h2100;
      8'h6F: pla3_mode8080 = 14'h2100;
      8'h70: pla3_mode8080 = 14'h2100;
      8'h71: pla3_mode8080 = 14'h2100;
      8'h72: pla3_mode8080 = 14'h2100;
      8'h73: pla3_mode8080 = 14'h2100;
      8'h74: pla3_mode8080 = 14'h2100;
      8'h75: pla3_mode8080 = 14'h2100;
      8'h76: pla3_mode8080 = 14'h290B;
      8'h77: pla3_mode8080 = 14'h2100;
      8'h78: pla3_mode8080 = 14'h2100;
      8'h79: pla3_mode8080 = 14'h2100;
      8'h7A: pla3_mode8080 = 14'h2100;
      8'h7B: pla3_mode8080 = 14'h2100;
      8'h7C: pla3_mode8080 = 14'h2100;
      8'h7D: pla3_mode8080 = 14'h2100;
      8'h7E: pla3_mode8080 = 14'h2100;
      8'h7F: pla3_mode8080 = 14'h2100;
      8'h80: pla3_mode8080 = 14'h2100;
      8'h81: pla3_mode8080 = 14'h2100;
      8'h82: pla3_mode8080 = 14'h2100;
      8'h83: pla3_mode8080 = 14'h2100;
      8'h84: pla3_mode8080 = 14'h2100;
      8'h85: pla3_mode8080 = 14'h2100;
      8'h86: pla3_mode8080 = 14'h2100;
      8'h87: pla3_mode8080 = 14'h2100;
      8'h88: pla3_mode8080 = 14'h2100;
      8'h89: pla3_mode8080 = 14'h2100;
      8'h8A: pla3_mode8080 = 14'h2100;
      8'h8B: pla3_mode8080 = 14'h2100;
      8'h8C: pla3_mode8080 = 14'h2100;
      8'h8D: pla3_mode8080 = 14'h2100;
      8'h8E: pla3_mode8080 = 14'h2100;
      8'h8F: pla3_mode8080 = 14'h2100;
      8'h90: pla3_mode8080 = 14'h2100;
      8'h91: pla3_mode8080 = 14'h2100;
      8'h92: pla3_mode8080 = 14'h2100;
      8'h93: pla3_mode8080 = 14'h2100;
      8'h94: pla3_mode8080 = 14'h2100;
      8'h95: pla3_mode8080 = 14'h2100;
      8'h96: pla3_mode8080 = 14'h2100;
      8'h97: pla3_mode8080 = 14'h2100;
      8'h98: pla3_mode8080 = 14'h2100;
      8'h99: pla3_mode8080 = 14'h2100;
      8'h9A: pla3_mode8080 = 14'h2100;
      8'h9B: pla3_mode8080 = 14'h2100;
      8'h9C: pla3_mode8080 = 14'h2100;
      8'h9D: pla3_mode8080 = 14'h2100;
      8'h9E: pla3_mode8080 = 14'h2100;
      8'h9F: pla3_mode8080 = 14'h2100;
      8'hA0: pla3_mode8080 = 14'h2100;
      8'hA1: pla3_mode8080 = 14'h2100;
      8'hA2: pla3_mode8080 = 14'h2100;
      8'hA3: pla3_mode8080 = 14'h2100;
      8'hA4: pla3_mode8080 = 14'h2100;
      8'hA5: pla3_mode8080 = 14'h2100;
      8'hA6: pla3_mode8080 = 14'h2100;
      8'hA7: pla3_mode8080 = 14'h2100;
      8'hA8: pla3_mode8080 = 14'h2100;
      8'hA9: pla3_mode8080 = 14'h2100;
      8'hAA: pla3_mode8080 = 14'h2100;
      8'hAB: pla3_mode8080 = 14'h2100;
      8'hAC: pla3_mode8080 = 14'h2100;
      8'hAD: pla3_mode8080 = 14'h2100;
      8'hAE: pla3_mode8080 = 14'h2100;
      8'hAF: pla3_mode8080 = 14'h2100;
      8'hB0: pla3_mode8080 = 14'h2100;
      8'hB1: pla3_mode8080 = 14'h2100;
      8'hB2: pla3_mode8080 = 14'h2100;
      8'hB3: pla3_mode8080 = 14'h2100;
      8'hB4: pla3_mode8080 = 14'h2100;
      8'hB5: pla3_mode8080 = 14'h2100;
      8'hB6: pla3_mode8080 = 14'h2100;
      8'hB7: pla3_mode8080 = 14'h2100;
      8'hB8: pla3_mode8080 = 14'h2100;
      8'hB9: pla3_mode8080 = 14'h2100;
      8'hBA: pla3_mode8080 = 14'h2100;
      8'hBB: pla3_mode8080 = 14'h2100;
      8'hBC: pla3_mode8080 = 14'h2100;
      8'hBD: pla3_mode8080 = 14'h2100;
      8'hBE: pla3_mode8080 = 14'h2100;
      8'hBF: pla3_mode8080 = 14'h2100;
      8'hC0: pla3_mode8080 = 14'h0000;
      8'hC1: pla3_mode8080 = 14'h0000;
      8'hC2: pla3_mode8080 = 14'h0000;
      8'hC3: pla3_mode8080 = 14'h0000;
      8'hC4: pla3_mode8080 = 14'h0000;
      8'hC5: pla3_mode8080 = 14'h0000;
      8'hC6: pla3_mode8080 = 14'h2000;
      8'hC7: pla3_mode8080 = 14'h0000;
      8'hC8: pla3_mode8080 = 14'h0000;
      8'hC9: pla3_mode8080 = 14'h0000;
      8'hCA: pla3_mode8080 = 14'h0000;
      8'hCB: pla3_mode8080 = 14'h0000;
      8'hCC: pla3_mode8080 = 14'h0000;
      8'hCD: pla3_mode8080 = 14'h0000;
      8'hCE: pla3_mode8080 = 14'h2000;
      8'hCF: pla3_mode8080 = 14'h0000;
      8'hD0: pla3_mode8080 = 14'h0000;
      8'hD1: pla3_mode8080 = 14'h0000;
      8'hD2: pla3_mode8080 = 14'h0000;
      8'hD3: pla3_mode8080 = 14'h200F;
      8'hD4: pla3_mode8080 = 14'h0000;
      8'hD5: pla3_mode8080 = 14'h0000;
      8'hD6: pla3_mode8080 = 14'h2000;
      8'hD7: pla3_mode8080 = 14'h0000;
      8'hD8: pla3_mode8080 = 14'h0000;
      8'hD9: pla3_mode8080 = 14'h0000;
      8'hDA: pla3_mode8080 = 14'h0000;
      8'hDB: pla3_mode8080 = 14'h200F;
      8'hDC: pla3_mode8080 = 14'h0000;
      8'hDD: pla3_mode8080 = 14'h0000;
      8'hDE: pla3_mode8080 = 14'h2000;
      8'hDF: pla3_mode8080 = 14'h0000;
      8'hE0: pla3_mode8080 = 14'h0000;
      8'hE1: pla3_mode8080 = 14'h0000;
      8'hE2: pla3_mode8080 = 14'h0000;
      8'hE3: pla3_mode8080 = 14'h0000;
      8'hE4: pla3_mode8080 = 14'h0000;
      8'hE5: pla3_mode8080 = 14'h0000;
      8'hE6: pla3_mode8080 = 14'h2000;
      8'hE7: pla3_mode8080 = 14'h0000;
      8'hE8: pla3_mode8080 = 14'h0000;
      8'hE9: pla3_mode8080 = 14'h0000;
      8'hEA: pla3_mode8080 = 14'h0000;
      8'hEB: pla3_mode8080 = 14'h0000;
      8'hEC: pla3_mode8080 = 14'h0000;
      8'hED: pla3_mode8080 = 14'h0801;
      8'hEE: pla3_mode8080 = 14'h2000;
      8'hEF: pla3_mode8080 = 14'h0000;
      8'hF0: pla3_mode8080 = 14'h0000;
      8'hF1: pla3_mode8080 = 14'h0000;
      8'hF2: pla3_mode8080 = 14'h0000;
      8'hF3: pla3_mode8080 = 14'h0805;
      8'hF4: pla3_mode8080 = 14'h0000;
      8'hF5: pla3_mode8080 = 14'h0000;
      8'hF6: pla3_mode8080 = 14'h2000;
      8'hF7: pla3_mode8080 = 14'h0000;
      8'hF8: pla3_mode8080 = 14'h0000;
      8'hF9: pla3_mode8080 = 14'h0000;
      8'hFA: pla3_mode8080 = 14'h0000;
      8'hFB: pla3_mode8080 = 14'h0804;
      8'hFC: pla3_mode8080 = 14'h0000;
      8'hFD: pla3_mode8080 = 14'h0000;
      8'hFE: pla3_mode8080 = 14'h2000;
      8'hFF: pla3_mode8080 = 14'h0000;
      default: pla3_mode8080 = 14'h0000;
    endcase
  endfunction

  // --- prefix 11: ext ---
  function automatic logic [13:0] pla3_ext(input logic [7:0] pla_op);
    case (pla_op)
      8'h00: pla3_ext = 14'h0000;
      8'h01: pla3_ext = 14'h0000;
      8'h02: pla3_ext = 14'h0000;
      8'h03: pla3_ext = 14'h0000;
      8'h04: pla3_ext = 14'h0000;
      8'h05: pla3_ext = 14'h0000;
      8'h06: pla3_ext = 14'h0000;
      8'h07: pla3_ext = 14'h0000;
      8'h08: pla3_ext = 14'h0000;
      8'h09: pla3_ext = 14'h0000;
      8'h0A: pla3_ext = 14'h0000;
      8'h0B: pla3_ext = 14'h0000;
      8'h0C: pla3_ext = 14'h0000;
      8'h0D: pla3_ext = 14'h0000;
      8'h0E: pla3_ext = 14'h0000;
      8'h0F: pla3_ext = 14'h0000;
      8'h10: pla3_ext = 14'h1100;
      8'h11: pla3_ext = 14'h1100;
      8'h12: pla3_ext = 14'h1100;
      8'h13: pla3_ext = 14'h1100;
      8'h14: pla3_ext = 14'h1100;
      8'h15: pla3_ext = 14'h1100;
      8'h16: pla3_ext = 14'h1100;
      8'h17: pla3_ext = 14'h1100;
      8'h18: pla3_ext = 14'h1100;
      8'h19: pla3_ext = 14'h1100;
      8'h1A: pla3_ext = 14'h1100;
      8'h1B: pla3_ext = 14'h1100;
      8'h1C: pla3_ext = 14'h1100;
      8'h1D: pla3_ext = 14'h1100;
      8'h1E: pla3_ext = 14'h1100;
      8'h1F: pla3_ext = 14'h1100;
      8'h20: pla3_ext = 14'h200A;
      8'h21: pla3_ext = 14'h200A;
      8'h22: pla3_ext = 14'h200A;
      8'h23: pla3_ext = 14'h200A;
      8'h24: pla3_ext = 14'h200A;
      8'h25: pla3_ext = 14'h200A;
      8'h26: pla3_ext = 14'h200A;
      8'h27: pla3_ext = 14'h200A;
      8'h28: pla3_ext = 14'h1180;
      8'h29: pla3_ext = 14'h1180;
      8'h2A: pla3_ext = 14'h1180;
      8'h2B: pla3_ext = 14'h1180;
      8'h2C: pla3_ext = 14'h1180;
      8'h2D: pla3_ext = 14'h1180;
      8'h2E: pla3_ext = 14'h1180;
      8'h2F: pla3_ext = 14'h1180;
      8'h30: pla3_ext = 14'h1583;
      8'h31: pla3_ext = 14'h1583;
      8'h32: pla3_ext = 14'h1583;
      8'h33: pla3_ext = 14'h1583;
      8'h34: pla3_ext = 14'h1583;
      8'h35: pla3_ext = 14'h1583;
      8'h36: pla3_ext = 14'h1583;
      8'h37: pla3_ext = 14'h1583;
      8'h38: pla3_ext = 14'h1583;
      8'h39: pla3_ext = 14'h1583;
      8'h3A: pla3_ext = 14'h1583;
      8'h3B: pla3_ext = 14'h1583;
      8'h3C: pla3_ext = 14'h1583;
      8'h3D: pla3_ext = 14'h1583;
      8'h3E: pla3_ext = 14'h1583;
      8'h3F: pla3_ext = 14'h1583;
      8'h40: pla3_ext = 14'h0000;
      8'h41: pla3_ext = 14'h0000;
      8'h42: pla3_ext = 14'h0000;
      8'h43: pla3_ext = 14'h0000;
      8'h44: pla3_ext = 14'h0000;
      8'h45: pla3_ext = 14'h0000;
      8'h46: pla3_ext = 14'h0000;
      8'h47: pla3_ext = 14'h0000;
      8'h48: pla3_ext = 14'h0000;
      8'h49: pla3_ext = 14'h0000;
      8'h4A: pla3_ext = 14'h0000;
      8'h4B: pla3_ext = 14'h0000;
      8'h4C: pla3_ext = 14'h0000;
      8'h4D: pla3_ext = 14'h0000;
      8'h4E: pla3_ext = 14'h0000;
      8'h4F: pla3_ext = 14'h0000;
      8'h50: pla3_ext = 14'h0000;
      8'h51: pla3_ext = 14'h0000;
      8'h52: pla3_ext = 14'h0000;
      8'h53: pla3_ext = 14'h0000;
      8'h54: pla3_ext = 14'h0000;
      8'h55: pla3_ext = 14'h0000;
      8'h56: pla3_ext = 14'h0000;
      8'h57: pla3_ext = 14'h0000;
      8'h58: pla3_ext = 14'h0000;
      8'h59: pla3_ext = 14'h0000;
      8'h5A: pla3_ext = 14'h0000;
      8'h5B: pla3_ext = 14'h0000;
      8'h5C: pla3_ext = 14'h0000;
      8'h5D: pla3_ext = 14'h0000;
      8'h5E: pla3_ext = 14'h0000;
      8'h5F: pla3_ext = 14'h0000;
      8'h60: pla3_ext = 14'h0000;
      8'h61: pla3_ext = 14'h0000;
      8'h62: pla3_ext = 14'h0000;
      8'h63: pla3_ext = 14'h0000;
      8'h64: pla3_ext = 14'h0000;
      8'h65: pla3_ext = 14'h0000;
      8'h66: pla3_ext = 14'h0000;
      8'h67: pla3_ext = 14'h0000;
      8'h68: pla3_ext = 14'h0000;
      8'h69: pla3_ext = 14'h0000;
      8'h6A: pla3_ext = 14'h0000;
      8'h6B: pla3_ext = 14'h0000;
      8'h6C: pla3_ext = 14'h0000;
      8'h6D: pla3_ext = 14'h0000;
      8'h6E: pla3_ext = 14'h0000;
      8'h6F: pla3_ext = 14'h0000;
      8'h70: pla3_ext = 14'h0000;
      8'h71: pla3_ext = 14'h0000;
      8'h72: pla3_ext = 14'h0000;
      8'h73: pla3_ext = 14'h0000;
      8'h74: pla3_ext = 14'h0000;
      8'h75: pla3_ext = 14'h0000;
      8'h76: pla3_ext = 14'h0000;
      8'h77: pla3_ext = 14'h0000;
      8'h78: pla3_ext = 14'h0000;
      8'h79: pla3_ext = 14'h0000;
      8'h7A: pla3_ext = 14'h0000;
      8'h7B: pla3_ext = 14'h0000;
      8'h7C: pla3_ext = 14'h0000;
      8'h7D: pla3_ext = 14'h0000;
      8'h7E: pla3_ext = 14'h0000;
      8'h7F: pla3_ext = 14'h0000;
      8'h80: pla3_ext = 14'h0000;
      8'h81: pla3_ext = 14'h0000;
      8'h82: pla3_ext = 14'h0000;
      8'h83: pla3_ext = 14'h0000;
      8'h84: pla3_ext = 14'h0000;
      8'h85: pla3_ext = 14'h0000;
      8'h86: pla3_ext = 14'h0000;
      8'h87: pla3_ext = 14'h0000;
      8'h88: pla3_ext = 14'h0000;
      8'h89: pla3_ext = 14'h0000;
      8'h8A: pla3_ext = 14'h0000;
      8'h8B: pla3_ext = 14'h0000;
      8'h8C: pla3_ext = 14'h0000;
      8'h8D: pla3_ext = 14'h0000;
      8'h8E: pla3_ext = 14'h0000;
      8'h8F: pla3_ext = 14'h0000;
      8'h90: pla3_ext = 14'h0000;
      8'h91: pla3_ext = 14'h0000;
      8'h92: pla3_ext = 14'h0000;
      8'h93: pla3_ext = 14'h0000;
      8'h94: pla3_ext = 14'h0000;
      8'h95: pla3_ext = 14'h0000;
      8'h96: pla3_ext = 14'h0000;
      8'h97: pla3_ext = 14'h0000;
      8'h98: pla3_ext = 14'h0000;
      8'h99: pla3_ext = 14'h0000;
      8'h9A: pla3_ext = 14'h0000;
      8'h9B: pla3_ext = 14'h0000;
      8'h9C: pla3_ext = 14'h0000;
      8'h9D: pla3_ext = 14'h0000;
      8'h9E: pla3_ext = 14'h0000;
      8'h9F: pla3_ext = 14'h0000;
      8'hA0: pla3_ext = 14'h0000;
      8'hA1: pla3_ext = 14'h0000;
      8'hA2: pla3_ext = 14'h0000;
      8'hA3: pla3_ext = 14'h0000;
      8'hA4: pla3_ext = 14'h0000;
      8'hA5: pla3_ext = 14'h0000;
      8'hA6: pla3_ext = 14'h0000;
      8'hA7: pla3_ext = 14'h0000;
      8'hA8: pla3_ext = 14'h0000;
      8'hA9: pla3_ext = 14'h0000;
      8'hAA: pla3_ext = 14'h0000;
      8'hAB: pla3_ext = 14'h0000;
      8'hAC: pla3_ext = 14'h0000;
      8'hAD: pla3_ext = 14'h0000;
      8'hAE: pla3_ext = 14'h0000;
      8'hAF: pla3_ext = 14'h0000;
      8'hB0: pla3_ext = 14'h0000;
      8'hB1: pla3_ext = 14'h0000;
      8'hB2: pla3_ext = 14'h0000;
      8'hB3: pla3_ext = 14'h0000;
      8'hB4: pla3_ext = 14'h0000;
      8'hB5: pla3_ext = 14'h0000;
      8'hB6: pla3_ext = 14'h0000;
      8'hB7: pla3_ext = 14'h0000;
      8'hB8: pla3_ext = 14'h0000;
      8'hB9: pla3_ext = 14'h0000;
      8'hBA: pla3_ext = 14'h0000;
      8'hBB: pla3_ext = 14'h0000;
      8'hBC: pla3_ext = 14'h0000;
      8'hBD: pla3_ext = 14'h0000;
      8'hBE: pla3_ext = 14'h0000;
      8'hBF: pla3_ext = 14'h0000;
      8'hC0: pla3_ext = 14'h0000;
      8'hC1: pla3_ext = 14'h0000;
      8'hC2: pla3_ext = 14'h0000;
      8'hC3: pla3_ext = 14'h0000;
      8'hC4: pla3_ext = 14'h0000;
      8'hC5: pla3_ext = 14'h0000;
      8'hC6: pla3_ext = 14'h0000;
      8'hC7: pla3_ext = 14'h0000;
      8'hC8: pla3_ext = 14'h0000;
      8'hC9: pla3_ext = 14'h0000;
      8'hCA: pla3_ext = 14'h0000;
      8'hCB: pla3_ext = 14'h0000;
      8'hCC: pla3_ext = 14'h0000;
      8'hCD: pla3_ext = 14'h0000;
      8'hCE: pla3_ext = 14'h0000;
      8'hCF: pla3_ext = 14'h0000;
      8'hD0: pla3_ext = 14'h0000;
      8'hD1: pla3_ext = 14'h0000;
      8'hD2: pla3_ext = 14'h0000;
      8'hD3: pla3_ext = 14'h0000;
      8'hD4: pla3_ext = 14'h0000;
      8'hD5: pla3_ext = 14'h0000;
      8'hD6: pla3_ext = 14'h0000;
      8'hD7: pla3_ext = 14'h0000;
      8'hD8: pla3_ext = 14'h0000;
      8'hD9: pla3_ext = 14'h0000;
      8'hDA: pla3_ext = 14'h0000;
      8'hDB: pla3_ext = 14'h0000;
      8'hDC: pla3_ext = 14'h0000;
      8'hDD: pla3_ext = 14'h0000;
      8'hDE: pla3_ext = 14'h0000;
      8'hDF: pla3_ext = 14'h0000;
      8'hE0: pla3_ext = 14'h0000;
      8'hE1: pla3_ext = 14'h0000;
      8'hE2: pla3_ext = 14'h0000;
      8'hE3: pla3_ext = 14'h0000;
      8'hE4: pla3_ext = 14'h0000;
      8'hE5: pla3_ext = 14'h0000;
      8'hE6: pla3_ext = 14'h0000;
      8'hE7: pla3_ext = 14'h0000;
      8'hE8: pla3_ext = 14'h0000;
      8'hE9: pla3_ext = 14'h0000;
      8'hEA: pla3_ext = 14'h0000;
      8'hEB: pla3_ext = 14'h0000;
      8'hEC: pla3_ext = 14'h0000;
      8'hED: pla3_ext = 14'h0000;
      8'hEE: pla3_ext = 14'h0000;
      8'hEF: pla3_ext = 14'h0000;
      8'hF0: pla3_ext = 14'h0000;
      8'hF1: pla3_ext = 14'h0000;
      8'hF2: pla3_ext = 14'h0000;
      8'hF3: pla3_ext = 14'h0000;
      8'hF4: pla3_ext = 14'h0000;
      8'hF5: pla3_ext = 14'h0000;
      8'hF6: pla3_ext = 14'h0000;
      8'hF7: pla3_ext = 14'h0000;
      8'hF8: pla3_ext = 14'h0000;
      8'hF9: pla3_ext = 14'h0000;
      8'hFA: pla3_ext = 14'h0000;
      8'hFB: pla3_ext = 14'h0000;
      8'hFC: pla3_ext = 14'h0000;
      8'hFD: pla3_ext = 14'h0000;
      8'hFE: pla3_ext = 14'h0000;
      8'hFF: pla3_ext = 14'h0000;
      default: pla3_ext = 14'h0000;
    endcase
  endfunction

  // Mode-selected lookup.  Prefix 10 is unused by the part and
  // returns the all-zero vector.
  function automatic logic [13:0] pla3_lookup(input logic [1:0] pla_mode,
                                              input logic [7:0] pla_op);
    case (pla_mode)
      PLA3_MODE_NATIVE: pla3_lookup = pla3_native(pla_op);
      PLA3_MODE_8080:   pla3_lookup = pla3_mode8080(pla_op);
      PLA3_MODE_EXT:    pla3_lookup = pla3_ext(pla_op);
      default:          pla3_lookup = 14'h0000;
    endcase
  endfunction

